### ISSUE TITLE
KITTI

### ISSUE THREAD

**Issue by einspyon** [vkee/loam_velodyne#1]
Hi, Had you tested LOAM on KITTI datasets successfully? 
 I had tried on it, but got totally wrong results, so came here to look for your advice, thanks!

**Comment by vkee** [comment]
Hi, 

I haven't tested it too much on KITTI. I haven't actively worked with this in a while, I would recommend reaching out to the developers on https://github.com/laboshinl/loam_velodyne for any advice.
